site_name: Infraestructura de Datos Espaciales FCyT UADER
site_description: Portal académico de datos, proyectos y productos geoespaciales de la FCyT
site_author: Fernando Tentor
site_url: https://ide-fcyt.github.io/IDE-FCyT/

# Repository
repo_name: IDE-FCyT/IDE-FCyT
repo_url: https://github.com/IDE-FCyT/IDE-FCyT
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright © 2021 - IDE FCyT UADER'

theme:
  name: material
  language: es
  logo: images/IDE_LOGO.svg
  favicon: images/favicon1.ico
  font:
    text: Google Sans
    code: Roboto Mono
  icon:
    logo: logo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: porto-primary-color
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: porto-primary-color
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo claro
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

extra_css:
  - css/custom.css

extra_javascript:
  - js/goatcounter.js

plugins:
  - search:
      lang: es

markdown_extensions:
  - md_in_html
  - attr_list
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IDE-FCyT
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/fcyt.uader/?hl=es
    - icon: fontawesome/solid/paper-plane
      link: mailto:<fcyt_ide@uader.edu.ar>
      name: "Contactanos"


nav:
  - Inicio: index.md
  - Catálogo: pages/catalog_index.md
  - Cómo usar la IDE: pages/Indicaciones_de_uso.md
  - Proyectos: pages/proyectos.md
  - Producción y divulgación: pages/produccion_divulgacion.md
  - Formación:
      - Maestría en Ciencia de Datos: pages/maestria.md
  - Institucional:
      - Acerca de la IDE: pages/acerca.md
      - CeReGeo: pages/ceregeo.md
      - Vinculaciones institucionales: pages/vinculaciones_institucionales.md
      - Portal de Acuicultura:
          - Inicio: pages/portal_acuicultura/index.md
          - El portal en imágenes: pages/portal_acuicultura/imagenes.md
          - Instituciones y redes: pages/portal_acuicultura/instituciones_y_redes.md
          - Nuestra carrera: pages/portal_acuicultura/carrera.md
          - Contacto: pages/portal_acuicultura/contacto.md
      - Contacto: pages/contacto.md
      - Lineamientos editoriales: pages/lineamientos_editoriales.md
