name: ci
on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force --clean
